fragment UserParts on User {
  __typename
  users {
    __typename
    username
    name
    email
    password {
      value
      passwordChangeRequired
    }
  }
}

fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksHero {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      tagline
      headline
      subheadline
      actions {
        __typename
        label
        type
        icon {
          __typename
          name
          color
          style
        }
        link
      }
      image {
        __typename
        src
        alt
        videoUrl
      }
    }
    ... on PageBlocksCallout {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      text
      url
    }
    ... on PageBlocksFeatures {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      items {
        __typename
        icon {
          __typename
          name
          color
          style
        }
        title
        text
        link
      }
    }
    ... on PageBlocksStats {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      stats {
        __typename
        stat
        type
      }
    }
    ... on PageBlocksCta {
      title
      description
      actions {
        __typename
        label
        type
        icon {
          __typename
          name
          color
          style
        }
        link
      }
    }
    ... on PageBlocksContent {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      id
      body
    }
    ... on PageBlocksTestimonial {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      testimonials {
        __typename
        quote
        author
        role
        avatar
      }
    }
    ... on PageBlocksVideo {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      color
      url
      autoPlay
      loop
    }
    ... on PageBlocksIndustriesGrid {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      industries {
        __typename
        icon {
          __typename
          name
          color
          style
        }
        image
        title
        description
        link
      }
    }
    ... on PageBlocksNewsFeed {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
    }
    ... on PageBlocksNewsArchive {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      searchPlaceholder
      emptyState
      ctaLabel
      ctaHref
      postsToLoad
    }
    ... on PageBlocksContactForm {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      text
    }
    ... on PageBlocksMap {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      embedCode
      description
    }
    ... on PageBlocksPropertyListing {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      ctaLabel
      ctaHref
    }
    ... on PageBlocksCommunityList {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      ctaLabel
    }
    ... on PageBlocksBoardDirectory {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      highlight
      title
      description
    }
    ... on PageBlocksResourceLibrary {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      ctaLabel
      ctaHref
    }
    ... on PageBlocksPropertyExplorer {
      style {
        __typename
        background
        padding
        width
        alignment
      }
      title
      description
      ctaLabel
      ctaHref
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  heroImg
  excerpt
  author {
    ... on Author {
      __typename
      name
      avatar
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  date
  tags {
    __typename
    tag {
      ... on Tag {
        __typename
        name
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
  _body
}

fragment AuthorParts on Author {
  __typename
  name
  avatar
}

fragment TagParts on Tag {
  __typename
  name
}

fragment GlobalParts on Global {
  __typename
  header {
    __typename
    icon {
      __typename
      name
      color
      style
    }
    name
    color
    nav {
      __typename
      href
      label
    }
    utility {
      __typename
      links {
        __typename
        label
        href
      }
      phoneLabel
      phoneNumber
      phoneHref
      actions {
        __typename
        label
        href
      }
    }
  }
  footer {
    __typename
    social {
      __typename
      icon {
        __typename
        name
        color
        style
      }
      url
    }
    newsletter {
      __typename
      title
      description
      buttonText
    }
    contact {
      __typename
      address
      phone
      email
    }
  }
  theme {
    __typename
    color
    font
    darkMode
  }
}

fragment PropertiesParts on Properties {
  __typename
  name
  type
  location
  size
  price
  utilities
  railAccess
  zoning
  description
  gallery
  specSheet
  contact
  status
}

fragment CommunitiesParts on Communities {
  __typename
  name
  population
  demographics
  description
  keyEmployers
  contactInfo
  profilePdf
  gallery
}

fragment BoardMembersParts on BoardMembers {
  __typename
  name
  title
  organization
  sector
  photo
  bio
  term
  committees
}

fragment ResourcesParts on Resources {
  __typename
  title
  description
  category
  file
  date
}
